language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
 - TRAVIS_NODE_VERSION=10 RUST_TOOLCHAIN=nightly

before_install:
 - yes | sdkmanager "platforms;android-27"
 - yes | sdkmanager "ndk-bundle"
 - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION;
 - gem update --system && gem install bundle && bundle install
 - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_TOOLCHAIN && source $HOME/.cargo/env
 - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
 - ./aw-server-rust/install-ndk.sh

install:
 # Build release build straight away if on a tagged commit, to avoid building twice
 - env RELEASE=$([ $TRAVIS_TAG ] && echo "true" || echo "false") make aw-server-rust

script:
 - bundle exec fastlane test
#- ./gradlew clean lint test
#- ./gradlew connectedAndroidTest || true

before_deploy:
 - openssl aes-256-cbc -K $encrypted_aac99b59139e_key -iv $encrypted_aac99b59139e_iv -in android.jks.enc -out android.jks -d
 - openssl aes-256-cbc -K $encrypted_c39c3bebf85c_key -iv $encrypted_c39c3bebf85c_iv -in fastlane/api-8546008605074111507-287154-450dc77b365f.json.enc -out fastlane/api-8546008605074111507-287154-450dc77b365f.json -d
 - env RELEASE=true make aw-server-rust  # RUSTFLAGS=-g # The RUSTFLAGS=-g is to keep debug symbols in the build, bloats the binary from 7M -> 60MB. Currently using profile.release.debug in Cargo.toml however as -g didn't work on the first try
 - make aw-webui
 - sed -i "s/versionName \".*\"/versionName \"$(echo $TRAVIS_TAG | tail -c +2 -)\"/g" mobile/build.gradle  # Sets versionName, tail used to skip "v" at start of tag name
 - env SUPPLY_TRACK=beta bundle exec fastlane update_version
 - bash scripts/build_apk.sh

deploy:
 # Production version
 - provider: script
   script: bundle exec fastlane supply run --apk aw-android*.apk --track beta
   skip_cleanup: true
   on:
     tags: true
     repo: ActivityWatch/aw-android
 - provider: releases
   file: aw-android*.apk
   file_glob: true
   skip_cleanup: true
   on:
     tags: true
     repo: ActivityWatch/aw-android
   api_key:
     secure: Z57ZwaWli8p8CN8VPeEWcOR1toG3rxNQfKhtdy5E7OWQnpTiurJgAUVwv1gn19rn+Ma3exzC0Qfne/APiIDNj5wmiGKIvxC8uVNO93Ta3OgJsXQie2UCIcNfZBLgWCNXssIijWz3d7J2xwNU8cBGz/F9wY0vVl5+TkEOrwJY2fjHJEsfGNF5zGgpsjJ6+FE2PBKKNhbdKk0SLKttmD6xJn77EsODS3pr8Xc1Q1FAm8uF+uPN4sOzdIgQINYQNEUHX9oB/Ejx+3LndQqijggl3MiVP3MIDwIV7kZjH0gDh4Yy4r26BGaRF8VQ9E0jKW/Rs98kMG+nwGdG/+UQA/887+PtPlT5V6XMUT5YmG/knV9CLZlxWqcNAt/mAQs1sKh5FXA0U8U2Q3E23LfTmoz0V3w67J+0XZYLS3PTN8H/vhTZUcQaobt+hWKvRDQ5q9pGfJknVtEaMfBxeYF6KJ03PdCJQOsa/AQtvsZeK6MkEESs2qVqfs86MRoqchA4o0QH2wx5Q6lZZghLEeBkVpU6qFBCRM29e3AlqJhjKT7c8jYg8IkZy5auuqIQoboRfNq+hKJEqnHClq5c52uM7ISRMapU2cOQZUpbOlzGP7I7E/eACRfDnLi2IdeKUd9xspEXf4r1j0sVhvlxl/bwLDhIhreySMTnWhT0qfFY7bVxIJM=
# Open beta (nightlys)
# TODO: Need to get latest versionCode using fastlane and set it (incremented) in the build.gradle
#- provider: script
#  script: bash scripts/deploy.sh
#  skip_cleanup: true
#  on:
#    branch: master

cache:
  directories:
   - $HOME/.cargo
   - $TRAVIS_BUILD_DIR/aw-server-rust/target

before_cache:
 - cargo install cargo-prune --force
 - cargo prune
